Proyecto/MascotasApp/src/java/modelo/CitasVetBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Luis
 */
@Named(value = "citasVet")
@SessionScoped
public class CitasVetBean implements Serializable {

    
    private String nombre;
    private List<String[]> citasPendientes;
    private Date searchDate;
    
    /**
     * Creates a new instance of CitasVetBean
     */
    public CitasVetBean() {
        
        this.nombre = "Rogelio Ruiz";
        this.citasPendientes = citasFactory();
        this.searchDate = new Date();
    }
    
    private List<String[]> citasFactory(){
        List<String[]> citas = new ArrayList();
        citas.add(new String[]{"26/05/2015","9:00 AM", "Penny","Luis Arriaga","Pendiente"});
        citas.add(new String[]{"26/05/2015","10:00 AM", "Manchas","Roberto Gómez","Pendiente"});
        citas.add(new String[]{"26/05/2015","12:00 PM", "Rex","Karla López","Pendiente"});
        citas.add(new String[]{"26/05/2015","15:00 PM", "Bestia","Rodolfo Arnulfo","Pendiente"});
        citas.add(new String[]{"26/05/2015","17:00 PM", "Dama","Paola Zárate","Pendiente"});
        citas.add(new String[]{"26/05/2015","18:00 PM", "Bigotes","Verónica Olmos","Pendiente"});
        return citas;
    }

    public String getNombre() {
        return "<b>Dr. "+nombre+"</b>";
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public List<String[]> getCitasPendientes() {
        return citasPendientes;
    }

    public void setCitasPendientes(List<String[]> citasPendientes) {
        this.citasPendientes = citasPendientes;
    }

    public int getTotalCitas(){
        return this.citasPendientes.size();
                
    }

    public Date getSearchDate() {
        return searchDate;
    }

    public void setSearchDate(Date searchDate) {
        this.searchDate = searchDate;
    }
    
    public Date getMinFecha(){
        return new Date();
    }
       
}

Proyecto/MascotasApp/web/Cliente/AgendarCita.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Ignorado</title>
    </h:head>
    <h:body>
        <ui:composition template="../templates/master.xhtml">
            <!--Si la página define estilos propios aquí se colocan (además de general.css)-->
            <ui:define name="estilos">
                <h:outputStylesheet library="css" name="citas.css"/>
            </ui:define>

            <!--Se define la barra de navegación-->
            <ui:define name="navBar">
                <ui:include src="../templates/navBars/NBCliente.xhtml"/>
            </ui:define>

            <!--Contenido de la vista-->
            <ui:define name="content">


                <br/>

                <p:panel id="viewContainer"
                         styleClass="panel-contenedor"
                         header="#{texto.citaHeaderAgendar}">

                    <h:panelGrid columns="2"
                                 styleClass="grid-container"
                                 columnClasses="calendar-container,hour-container">

                        <h:panelGroup layout="block">
                            <h:form id="fechaForm">
                                <p:outputPanel id="dateContainer"
                                               styleClass="time-container">

                                    <div align="center">
                                        <p:outputLabel value="#{texto.citaElijeFecha}"/>
                                        <p:separator/>
                                        <p:calendar mode="inline" 
                                                    locale="es"
                                                    value="#{agendaCita.fechaBusqueda}"
                                                    mindate="#{agendaCita.minFecha}"/>
                                        <br/>
                                        <p:commandButton value="#{texto.citaBuscar}"
                                                         id="buscarFecha"
                                                         icon="ui-icon-search"
                                                         update=":horasForm"/>
                                        <br/>
                                        <br/>
                                    </div>

                                </p:outputPanel>
                            </h:form>

                        </h:panelGroup>

                        <h:panelGroup layout="block">

                            <h:form id="horasForm">
                                <p:outputPanel id="horasContainer"
                                               styleClass="time-container">

                                    <div align="center" class="horas-table-container">
                                        <p:outputLabel value="#{texto.citaAgendaPara} "/>
                                        <p:outputLabel value="#{agendaCita.fechaBusqueda}">
                                            <f:convertDateTime pattern="dd/MM/yyyy"/>
                                        </p:outputLabel>
                                        <p:separator />
                                        <p:dataTable id="horasTable"
                                                     value="#{agendaCita.horasDia}"
                                                     var="hora"
                                                     emptyMessage="#{texto.citaSinHora}"
                                                     tableStyleClass="horas-table">
                                            <p:column headerText="#{texto.citaHora}">
                                                <p:outputLabel value="#{hora[0]}"/>
                                            </p:column>

                                            <p:column headerText="#{texto.citaEstado}"
                                                      styleClass="#{hora[2]}"
                                                      >
                                                <p:outputLabel value="#{hora[1]}"/>
                                            </p:column>

                                            <p:column headerText="#{texto.citaAccion}">

                                                <p:commandButton icon="ui-icon-pencil"
                                                                 update=":detallesForm"
                                                                 onclick="PF('detalleCita').show();">

                                                    <f:setPropertyActionListener value="#{hora[0]}" target="#{agendaCita.horaCita}"/>
                                                </p:commandButton>

                                            </p:column>
                                        </p:dataTable>

                                    </div>

                                </p:outputPanel>

                                <p:blockUI block="horasForm" trigger=":fechaForm:buscarFecha">
                                    #{texto.citaRecuperaAgenda}<br/>
                                    <p:graphicImage library="imagenes" name="loader.gif"/>
                                </p:blockUI>

                            </h:form>

                        </h:panelGroup>


                    </h:panelGrid>
                </p:panel>

                <p:dialog widgetVar="detalleCita"
                          header="#{texto.citaDetalleCita}"
                          draggable="false"
                          showEffect="fade"
                          resizable="false"
                          dynamic="true"
                          modal="true"
                          appendTo="@(body)">

                    <h:form id="detallesForm">
                        <h:panelGrid columns="4">
                            <p:outputLabel value="#{texto.citaFecha}"/>
                            <p:inputText disabled="true"
                                         value="#{agendaCita.fechaBusqueda}">
                                <f:convertDateTime pattern="dd/MM/yyyy"/>
                            </p:inputText>

                            <p:outputLabel value="#{texto.citaHoraForm}"/>
                            <p:inputText disabled="true" 
                                         value="#{agendaCita.horaCita}"/>
                        </h:panelGrid>

                        <p:separator/>

                        <h:panelGrid columns="2">

                            <p:outputLabel value="#{texto.citaSelecMascotaLabel}"/>
                            <h:panelGroup>
                                <p:selectOneMenu id="mascota"
                                                 value="#{agendaCita.mascota}"
                                                 required="true"
                                                 requiredMessage="#{texto.citaMascotaRequired}">
                                    <f:selectItem itemValue="" itemLabel="#{texto.citaMenuMascota}" noSelectionOption="true"/>
                                </p:selectOneMenu>
                                <p:message for="mascota"/>
                            </h:panelGroup>

                            <p:outputLabel value="#{texto.citaMotivoLabel}"/>
                            <h:panelGroup>
                                <p:selectOneMenu id="motivo"
                                                 value="#{agendaCita.motivo}"
                                                 required="true"
                                                 requiredMessage="#{texto.citaMotivoRequired}">
                                    <f:selectItem itemValue="" itemLabel="#{texto.citaMenuMotivo}" noSelectionOption="true"/>
                                </p:selectOneMenu>
                                <p:message for="motivo"/>
                            </h:panelGroup>


                            <p:outputLabel value="#{texto.citaVeterinarioLabel}"/>
                            <h:panelGroup>
                                <p:selectOneMenu id="veterinario"
                                                 value="#{agendaCita.veterinario}"
                                                 required="true"
                                                 requiredMessage="#{texto.citaVeterinarioRequired}">
                                    <f:selectItem itemValue="" itemLabel="#{texto.citaMenuVet}" noSelectionOption="true"/>
                                </p:selectOneMenu>
                                <p:message for="veterinario"/>
                            </h:panelGroup>
                        </h:panelGrid>

                        <p:separator />
                        <p:outputLabel value="#{texto.citaObser}"/><br/>                            
                        <p:inputTextarea id="observaciones"
                                         value="#{agendaCita.observaciones}"
                                         style="width:100%;"
                                         rows="3"
                                         autoResize="false"
                                         maxlength="250"
                                         counter="observacionesChar"
                                         counterTemplate="#{texto.citaRestantes}"
                                         validatorMessage="#{texto.citaObsValidator}">
                            <f:validateRegex pattern="[a-zA-Z\\s\\.,;áéíóúüÁÉÍÓÚÜ]+"/>
                        </p:inputTextarea>
                        <p:outputLabel id="observacionesChar"/>
                        <p:message for="observaciones"/>
                        <br/>
                        <br/>
                        <div align="center">
                            <p:commandButton icon="ui-icon-close"
                                             type="button"
                                             value="#{texto.citaCancelar}"
                                             onclick="PF('detalleCita').hide();"/>
                            <p:commandButton icon="ui-icon-check" 
                                             value="#{texto.citaAgendar}"
                                             update="detallesForm"/>
                        </div>


                    </h:form>

                </p:dialog>


                <!--Se define el archivo js con la traducción a español del calendar-->
                <h:outputScript library="js" name="calendar-es.js"/>

            </ui:define>
        </ui:composition>
    </h:body>
</html>


Proyecto/MascotasApp/web/Cliente/VerCitas.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Ignorado</title>
    </h:head>
    <h:body>

        <ui:composition template="../templates/master.xhtml">
            <!--Si la página define estilos propios aquí se colocan (además de general.css)-->
            <ui:define name="estilos">
                <h:outputStylesheet library="css" name="citas.css"/>
            </ui:define>

            <!--Se define la barra de navegación-->
            <ui:define name="navBar">
                <ui:include src="../templates/navBars/NBCliente.xhtml"/>
            </ui:define>

            <!--Contenido de la vista-->
            <ui:define name="content">
                <br/>

                <p:panel id="viewContainer"
                         styleClass="panel-contenedor"
                         header="#{texto.citaCitasPendientes}">

                    <div align="center" 
                         class="citas-table-container">

                        <p:outputLabel value="#{texto.citaCitasPara}"/>
                        <br/>
                        <p:outputLabel value="#{citasCliente.nombre}"
                                       escape="false"/>
                        <br/>
                        <br/>

                        <div align="left">
                            <p:outputLabel value="#{texto.citaTotalCitas} #{citasCliente.totalCitas}"/>
                        </div>
                        <h:form id="citasForm">
                            <p:dataTable id="citasPendientesTable"
                                         value="#{citasCliente.citasPendientes}"
                                         var="cita"
                                         tableStyleClass="horas-table"
                                         paginator="true"
                                         paginatorPosition="bottom"
                                         rows="5"
                                         emptyMessage="#{texto.citaSinCitasCliente}"
                                         currentPageReportTemplate="#{texto.citaCitasMostradas}">
                                <p:column headerText="#{texto.citaFecha}">

                                    <p:outputLabel value="#{cita[0]}"/>

                                </p:column>

                                <p:column headerText="#{texto.citaHora}">
                                    <p:outputLabel value="#{cita[1]}"/>
                                </p:column>

                                <p:column headerText="#{texto.citaNombreMasc}">
                                    <p:outputLabel value="#{cita[2]}"/>
                                </p:column>

                                <p:column headerText="#{texto.citaEstatus}">

                                    <p:outputLabel value="#{cita[3]}"/>

                                </p:column>

                                <p:column headerText="#{texto.citaAccion}">

                                    <p:commandButton icon="ui-icon-plus"
                                                     onclick="PF('detalleCita').show()"/>

                                </p:column>
                            </p:dataTable>

                        </h:form>

                    </div>



                </p:panel>


                <p:dialog widgetVar="detalleCita"
                          header="#{texto.citaDetalleCita}"
                          draggable="false"
                          showEffect="fade"
                          resizable="false"
                          dynamic="true"
                          modal="true"
                          appendTo="@(body)">

                    <h:panelGrid columns="4">
                        <p:outputLabel value="#{texto.citaFecha}"/>
                        <p:inputText readonly="true"
                                     value="26/05/2016">
                            <f:convertDateTime pattern="dd/MM/yyyy"/>
                        </p:inputText>

                        <p:outputLabel value="#{texto.citaHoraForm}"/>
                        <p:inputText readonly="true" 
                                     value="9:00 AM"/>
                    </h:panelGrid>

                    <p:separator />

                    <h:panelGrid columns="4">
                        <p:outputLabel value="#{texto.citaMascotaForm}"/>
                        <p:inputText value="Manchas"
                                     readonly="true"/>
                        <p:outputLabel value="#{texto.citaEstatusForm}"/>
                        <p:inputText value="Pendiente"
                                     readonly="true"/>
                        <p:outputLabel value="#{texto.citaMotivoForm}"/>
                        <p:inputText value="Consulta"
                                     readonly="true"
                                     />

                    </h:panelGrid>

                    <p:separator/>
                    <p:outputLabel value="#{texto.citaObser}"/>
                    <p:inputTextarea id="observaciones"
                                     value="Algunas observaciones"
                                     style="width:100%;"
                                     rows="3"
                                     autoResize="false"
                                     readonly="true"
                                     >
                    </p:inputTextarea>
                    <p:separator/>
                    <div align="center">
                        <p:commandButton value="#{texto.citaCerrar}"
                                         type="button"
                                         icon="ui-icon-close"
                                         onclick="PF('detalleCita').hide();"/>
                    </div>



                </p:dialog>

            </ui:define>
        </ui:composition>
    </h:body>
</html>


Proyecto/MascotasApp/web/Cliente/iniCliente.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Menu Cliente</title>
    </h:head>
    <h:body>
        <ui:composition template="/templates/master.xhtml">

            <ui:define name="estilos">
            </ui:define>
           <ui:define name="navBar">
                <ui:include src="/templates/navBars/NBCliente.xhtml"/>
            </ui:define>

            <!--Contenido de la vista-->
            <ui:define name="content">
                <br/>
                <p:panel header="Bienvenido" 
                    styleClass="panel-contenedor">

                    <div align="center">
                        <p:outputLabel value=""/>
                        <br/>
                        <p:outputLabel value=""/>
                    </div>
                </p:panel>                
            </ui:define>


        </ui:composition>
    </h:body>
</html>